V2 airflow dbt solution
Aginic/wfs-airflow-dbt pull request #1
Opened 2023-03-19 23:13 UTC by pira04

Here is little version of dbt + airflow project  for review

2023-03-19 23:29 UTC, sanjayio requested changes
Overall really good work! I have left some comments (some are nitpicks), it would be good if you could change them as well!

2023-03-19 23:29 UTC, sanjayio commented on airflow/requirements.txt
> +dbt-core==1.2.0
Nit: I think `dbt-core` is redundant here as its already installed with `dbt-snowflake`

2023-03-19 23:29 UTC, sanjayio commented on dags/demo_dag.py
> +DBT_PROFILES_DIR = 'wfs_snowflake'
Nit: Would be good to add absolute paths here, instead of relative paths.

2023-03-19 23:29 UTC, sanjayio commented on dags/demo_dag.py
> +        bash_command=f"cd {DBT_PROJECT_DIR} && dbt deps --profiles {DBT_PROFILES_DIR}"
This works, but I think its best to stick with dbt recommended approach to use `--profiles-dir` and `--project-dir` instead of `cd`. This can be replaced with `dbt deps --profiles-dir {DBT_PROFILES_DIR} --project-dir {DBT_PROJECT_DIR}`

2023-03-19 23:29 UTC, sanjayio commented on dags/demo_dag.py
> +        bash_command=f'cd {DBT_PROJECT_DIR} && dbt compile --profile {DBT_PROFILES_DIR}'
Same here

2023-03-19 23:29 UTC, sanjayio commented on dags/demo_dag.py
> +        bash_command=f'cd {DBT_PROJECT_DIR} && dbt run --profile {DBT_PROFILES_DIR}',
same here

2023-03-19 23:29 UTC, sanjayio commented on docker-compose.yaml
> +    - ./wfs_snowflake:/opt/wfs_snowflake
Nit: Should be rename this to dbt ? As the name `wfs_snowflake` is not a clear indicator of a dbt project.

2023-03-19 23:29 UTC, sanjayio commented on wfs_snowflake/dbt_project.yml
> +name: 'wfs_snowflake'
Nit: I would recommend not using the underlying DW provider in the name of the dbt project, since that would make it closely tied to the technology. Names that are technology agnostic, would be ideal, because in the future if wfs decides to swap out snowflake with some other DW, we wouldn't have to change this.

2023-03-19 23:29 UTC, sanjayio commented on wfs_snowflake/dbt_project.yml
> +  wfs_snowflake:
Same here

2023-03-19 23:29 UTC, sanjayio commented on docker-compose.yaml
> +    AIRFLOW__CORE__EXECUTOR: LocalExecutor
Why do we want to change this ?

2023-03-20 00:27 UTC, pira04 commented on airflow/requirements.txt
> +dbt-core==1.2.0
resolved

2023-03-20 00:27 UTC, pira04 commented on dags/demo_dag.py
> +        bash_command=f"cd {DBT_PROJECT_DIR} && dbt deps --profiles {DBT_PROFILES_DIR}"
resolved

2023-03-20 00:27 UTC, pira04 commented on dags/demo_dag.py
> +        bash_command=f'cd {DBT_PROJECT_DIR} && dbt compile --profile {DBT_PROFILES_DIR}'
resolved

2023-03-20 00:27 UTC, pira04 commented on dags/demo_dag.py
> +        bash_command=f'cd {DBT_PROJECT_DIR} && dbt run --profile {DBT_PROFILES_DIR}',
resolved

2023-03-20 00:27 UTC, pira04 commented on docker-compose.yaml
> +    - ./wfs_snowflake:/opt/wfs_snowflake
resolved

2023-03-20 00:28 UTC, pira04 commented on wfs_snowflake/dbt_project.yml
> +name: 'wfs_snowflake'
resolved

2023-03-20 00:28 UTC, pira04 commented on wfs_snowflake/dbt_project.yml
> +  wfs_snowflake:
resolved

2023-03-20 00:28 UTC, pira04 commented on docker-compose.yaml
> +    AIRFLOW__CORE__EXECUTOR: LocalExecutor
resolved

2023-03-20 00:28 UTC, closed without merging